# Generated by Django 2.1.4 on 2019-01-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('sendtxt', models.CharField(max_length=255)),
                ('times', models.CharField(max_length=50)),
                ('sendtime', models.CharField(max_length=50)),
                ('photoname', models.FileField(upload_to='photo')),
                ('musicname', models.FileField(upload_to='music')),
            ],
        ),
    ]
